# Generated by Django 5.1.2 on 2024-10-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('LoanID', models.IntegerField(primary_key='LoanID', serialize=False)),
                ('LoanAmt', models.FloatField()),
                ('DoB', models.DateField()),
                ('PhNo', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
