# Generated by Django 5.1.2 on 2024-10-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thamana', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='PhNo',
            new_name='AccNo',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='DoB',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='Email',
        ),
    ]
