# Generated by Django 5.1.2 on 2024-11-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thamana', '0002_rename_phno_loan_accno_remove_loan_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
